### ISSUE TITLE
Can’t log in with Liberty Woof account

### ISSUE THREAD

**Issue by Jayman2000** [bit-badger/jobs-jobs-jobs#29]
I’m trying to log in with my Liberty Woof account. After I click “Authorize”, it says “Welcome back! Verifying your Liberty Woof account…”, and then after a while it says “Error logging on -
504 Gateway Time-out”.

**Comment by danieljsummers** [comment]
Looking into this; I know it worked at one point...

**Comment by danieljsummers** [comment]
This works from my development machine, which points to something between the server where JJJ is hosted and Liberty Woof's servers. I'll keep you updated as I have a chance to look into it later this evening.

**Comment by danieljsummers** [comment]
Do you run this instance? If so, the below may help; if not, feel free to point me in the right direction.

* The servers can see each other

From the server hosting JJJ, `curl https://libertywoof.com` gave me the page that redirects me to the about page (which is expected; I'm not logged on to LW from my server's command line). This tells me that the two servers can see each other over HTTPS from a request initiated by the server.

* The URL to which JJJ is posting its request is valid

I put logging in the code to show what URL is actually created at the time of trying to verify credentials, and it's `POST https://libertywoof.com/oauth/token` (see the second entry at [this page](https://docs.joinmastodon.org/methods/apps/oauth/) in the Mastodon API documentation).

* Logging on via LW works from my development machine

...and it's really fast! This is what's pointing me to it being a network issue. The app configuration is identical among the 3 instances, with the exception of where the return token comes; for that, I use one of `nas`, `itm`, or `lw` so that I know with which instance I need to verify credentials. I also know, from my development experience, that Mastodon is quick to return errors if your request isn't right; it doesn't just dump them into a black hole.

* `traceroute` from both servers fails at the Internet entry point

Depending on your server's configuration, this isn't necessarily a problem; a lot of servers block ICMP (the protocol that it uses to determine the route a request takes between the source and destination). This demonstrates that there's nothing blocking within each network.

---

Given all that, that's about all I can see from my end. I'd like to work with the server maintainer to see if they can see anything on their end - does that `POST` actually show in the logs? Was there some prior attack from a similar IP range that ended up with this IP in a firewall `DENY` list somehow? Those are the sorts of things I'd be looking into on the destination side.

**Comment by Jayman2000** [comment]
> Do you run this instance? If so, the below may help; if not, feel free to point me in the right direction.

No, I don’t. [This page](https://libertywoof.com/about/more) gives contact information for who runs Liberty Woof.

I just tried logging in again. Now, I get “Error logging on - "The request was canceled due to the configured HttpClient.Timeout of 20 seconds elapsing."”

**Comment by danieljsummers** [comment]
@Jayman2000 Yes - I changed the timeout so that it would fail more quickly (and waste less time). I plan to change that to 30 seconds permanently.

Thanks again for reporting this, and for the contact info. I had tested this all out, but I didn't need 3 different employment profiles, so I hadn't logged in with all 3 instances once I actually put it out live.

**Comment by danieljsummers** [comment]
Do you know if Liberty Woof has shut down? The domain is still registered, but there's no `A` record (IPv4 DNS record), and no server at its IPv6 `AAAA` record's address.

**Comment by Jayman2000** [comment]
> Do you know if Liberty Woof has shut down? The domain is still registered, but there's no `A` record (IPv4 DNS record), and no server at its IPv6 `AAAA` record's address.

Honestly, I don’t really know anything about Liberty Woof (or the fediverse in general). I only created an account there because I didn’t already have a fediverse account when I first tried out Jobs, Jobs, Jobs.

**Comment by danieljsummers** [comment]
Got it - thanks for replying so quickly! I'll leave this open for a bit longer until I can get confirmation; or, if there's resounding silence, maybe that's my answer.

ITM, Slaves! has open registration; however, they shifted platforms and the integration is a little borked up right now. #33 (yes, it's issue 33... LOL) I hope to get that resolved at some point this month.

**Comment by danieljsummers** [comment]
There has been no response on the provenance of Liberty Woof. As v3 will not have this dependency, I'll focus my efforts there.
